Compile library using latest Android Studio Preview with androidx
h6ah4i/android-advancedrecyclerview pull request #456
Opened 2018-06-14 17:39 UTC by pn

2018-07-10 11:39 UTC, pn commented
I made some changes that should make example compile on AS 3.2-beta2 (previous commits were meant only for the library) but It will still crash on runtime. To fix that h6ah4i/android-tablayouthelper needs to be migrated to androidx. I'm not planning to do it anytime soon.

2018-09-30 12:42 UTC, h6ah4i requested changes
Thanks for your great pull request :+1: :+1: :+1: 

I noticed that some dependencies in `build.gradle` can be replaced with more better ones. If you fix them, I'll merge this PR.

2018-09-30 12:42 UTC, h6ah4i commented on example/build.gradle
>      implementation ('com.h6ah4i.android.tablayouthelper:tablayouthelper:0.9.0')
Please tweak here like the following:
```diff
-    implementation 'com.google.android.material:material:1.0.0-beta01'
-    implementation ('com.h6ah4i.android.tablayouthelper:tablayouthelper:0.9.0')
+    implementation 'com.google.android.material:material:1.0.0'
+    implementation 'com.h6ah4i.android.tablayouthelper:tablayouthelper:1.0.0'
```

2018-09-30 12:42 UTC, h6ah4i commented on library/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.0.0-beta01'
Replace these lines like this;
```diff
-    implementation 'androidx.appcompat:appcompat:1.0.0-beta01'
-    implementation 'androidx.recyclerview:recyclerview:1.0.0-beta01'
+    implementation ('androidx.recyclerview:recyclerview:1.0.0') {
+        exclude group: 'androidx.legacy', module: 'legacy-support-core-ui'
+    }
```

2018-09-30 14:40 UTC, h6ah4i commented
Oh, I noticed one more issue in comment blocks. Need to correct RecyclerView's package.

```diff
-androidx.appcompat.widget.RecyclerView
+androidx.recyclerview.widget.RecyclerView
```

2018-10-03 04:56 UTC, Suki-VT commented
Is it solved ?

2018-10-05 09:34 UTC, pn commented
@h6ah4i, thank you for review. Please check recent changes.

2018-10-06 05:29 UTC, h6ah4i approved these changes

2018-10-06 05:30 UTC, h6ah4i commented
LGTM :+1: :+1: :+1:

2018-10-06 05:30 UTC, merged